extends:
  - plugin:astro/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
overrides:
  - files:
      - '*.astro'
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .astro
    rules: {}
  - files:
      - '*.svelte'
    processor: svelte3/svelte3
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .svelte
    rules: {}
    settings:
      svelte3/typescript: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - svelte3
  - '@typescript-eslint'
ignorePatterns:
  - './dist/**/*'
